databases/config/routes.rb
Rails.application.routes.draw do
  # FRONTEND
  # ------------------------------------------------------------------
  root to: 'public/base#index'
  get '/', to: 'public/base#index'

  # Search
  get '/search(/:page)', to: 'public/search#index'

  # Feedback
  get '/feedback(/:db_id)', to: 'public/feedback#index'
  post '/feedback', to: 'public/feedback#email_submission'

  # Reporting
  get '/report(/:db_id)', to: 'public/report#index'
  post '/report', to: 'public/report#error_report'

  # A to Z Listings
  get '/AtoZ', to: 'public/base#all'
  get '/AtoZ/:character', to: 'public/base#a_to_z'

  # Subject Listings
  get '/subject', to: 'public/base#subject'
  get '/subjects', to: 'public/base#subject'
  get '/databases/subjects', to: redirect('/subjects')
  get '/subject/:id', to: 'public/base#subject_databases'

  # landing pages
  get '/about/:uuid', to: 'public/about#index'

  # url connection
  get '/connect/:uuid', to: 'public/connect#index'

  # CAS
  # ------------------------------------------------------------------
  get '/login',
      to: 'application#login',
      as: 'login'

  get '/signout',
      to: 'application#signout',
      as: 'signout'

  get '/logout',
      to: 'application#logout',
      as: 'logout'

  # ADMIN
  # ------------------------------------------------------------------
  get '/admin', to: 'admin#home', as: 'admin'

  namespace :admin do
    # databases
    get '/databases/list', to: 'databases#listall'
    get '/databases/list/:status', to: 'databases#list'
    get '/databases/tables', to: 'databases#tables'
    get '/databases/tables/:status', to: 'databases#tables'
    get '/databases/libguides', to: 'databases#lib_guides'
    resources :databases

    # import databases
    get '/import', to: 'databases#import'
    post '/import', to: 'databases#csv_import'

    # vendors
    resources :vendors

    # resources
    resources :resources

    # subjects
    resources :subjects
    get '/curated', to: 'subjects#curated', as: 'curated'
    get '/curated/:subject/sort', to: 'subjects#sort', as: 'sort_curated'
    post '/curated', to: 'subjects#update_curated', as: 'update_curated'

    # landing pages
    resources :landing_pages

    # users
    resources :users

    # link tracking
    resources :link_tracking

    # statistics
    get '/stats', to: 'statistics#show_all', as: 'csv_stats_all'
    get '/stats/:start_date/:end_date', to: 'statistics#show', as: 'csv_stats_filtered'
    #resources :statistics

    # get '/stats' to: 'statistics#show_all', as: 'stats'

    # admin/stats/10-22-2018/10-22-2021
    # get '/stats/:start_date/:end_date', to: 'statistics#show'
    # get 'stats' to: 'statistics#show_all'
  end
end

databases/app/views/admin/_navigation.html.erb
<nav id="offCanvas" class="offcanvas-left" role="navigation">
  
  <header>
    <h2> Menu </h2>
    <a href="javascript:void(0)" class="button close-button" title="close">
      <span class='fa fa-times-circle'></span>
    </a>
  </header>

  <ul>
    <li> <a href="/"> <span class='fa fa-home'></span> Public </a> </li>
    <li> <a href="/admin"><span class='fa fa-home'></span> Admin </a> </li>
    <!-- Card View Lists -->
    <li class="title"> <h3> Database(s) </h3></li> 
    <li> <%= link_to 'New Database', new_admin_database_path %> </li>
    <li> All (
      <a href="/admin/databases/list" aria-label="List All"> List </a> | 
      <a href="/admin/databases/tables" aria-label="List all as Tables"> Table </a>
    )
    </li>
    <li> Public (
      <a href="/admin/databases/list/production" aria-label="List for Public"> List </a> |
      <a href="/admin/databases/tables/production" aria-label="Table list for Public"> Table </a>
    )
    </li>
    <li> Development (
      <a href="/admin/databases/list/development" aria-label="List for Development"> List </a> |
      <a href="/admin/databases/tables/development" aria-label="Table list for Development"> Table </a>
    )
    </li>
    <li> Hidden (
      <a href="/admin/databases/list/hidden" aria-label="List for Hidden"> List </a> |
      <a href="/admin/databases/tables/hidden" aria-label="Table list for Hidden"> Table </a>
    )
    </li>
    
    <!-- Management -->
    <li class="title"> <h3> Resource(s) </h3> </li>
    <li> <%= link_to 'New Resource', new_admin_resource_path %>
    <li> <a href="/admin/resources"> Resource List </a></li>
    <li class="title"> <h3> Subject(s) </h3> </li>
    <li> <%= link_to 'New Subject', new_admin_subject_path %>
    <li> <a href="/admin/subjects"> Subject List </a></li>
    
    <!-- Vendor -->
    <li class="title"> <h3>Vendor(s)</h3> </li>
    <li> <%= link_to 'New Vendor', new_admin_vendor_path %> </li>
    <li> <a href="/admin/vendors"> Vendor List </a></li>
    
    <!-- Landing Pages -->
    <li class="title"> <h3>Landing Pages</h3> </li>
    <li> <%= link_to 'New Landing Page', new_admin_landing_page_path %> </li>
    <li> <a href="/admin/landing_pages"> Landing Pages List </a></li>
    
    <!-- User Management  -->
    <li class="title"> <h3>User Management</h3> </li>
    <li> <%= link_to 'Add User Access', new_admin_user_path %> </li>
    <li> <a href="/admin/users"> Manage Users </a></li>
    
    <!-- Reporting -->
    <li class="title"><h3>Exporting </h3>  </li>
    <li> <a href="/admin/databases.csv"> Database(s) CSV Report </a> </li>
    <li> <a href="/admin/stats"> Database(s) Usage CSV Export </a> </li>    
    <li> <a href="/admin/databases/libguides.csv"> LibGuides CSV Export </a> </li>    

    <!-- Reporting -->
    <li class="title"><h3> Importing </h3>  </li>
    <li> <a href="/admin/import"> Database Import </a> </li>

    <!-- Reporting -->
    <li class="title"><h3> Database Usage </h3>  </li>
    <li> <a href="/admin/link_tracking"> Database Usage Stats </a> </li>
  </ul>
</nav>

databases/app/views/admin/index.html.erb
<h2> Welcome, <%= session['cas']['extra_attributes']['displayName'] unless session['cas'].nil? %> </h2>

<p> Welcome to the admin panel for the LibDataBase application. The main admin interface is powered by the big menu button in the top right corner of the page.  This is where you will find links to manage the databases, vendors, users, and other critical aspects of this application.  </p> <br/>

<h3> Github Development and Documentation </h3>

<div class="github-actions"> 
  <a href="https://github.com/wvulibraries/databases" class="github-button"> <span class="fas fa-file-alt"></span> Documentation </a>
  <a href="https://github.com/wvulibraries/databases/issues/new?template=bug_report.md" class="github-button bug-button"> <span class="fa fa-bug"></span> Bug Report </a>
  <a href="https://github.com/wvulibraries/databases/issues/new?template=feature_request.md" class="github-button feature-button"> <span class="fa fa-microchip" aria-hidden="true"></span>
 Feature Request </a>
</div>