databases/config/routes.rb
Rails.application.routes.draw do
  # FRONTEND
  # ------------------------------------------------------------------
  root to: 'public/base#index'
  get '/', to: 'public/base#index'

  # Search
  get '/search(/:page)', to: 'public/search#index'

  # Feedback
  get '/feedback(/:db_id)', to: 'public/feedback#index'
  post '/feedback', to: 'public/feedback#email_submission'

  # Reporting
  get '/report(/:db_id)', to: 'public/report#index'
  post '/report', to: 'public/report#error_report'

  # A to Z Listings
  get '/AtoZ', to: 'public/base#all'
  get '/AtoZ/:character', to: 'public/base#a_to_z'

  # Subject Listings
  get '/subject', to: 'public/base#subject'
  get '/subjects', to: 'public/base#subject'
  get '/databases/subjects', to: redirect('/subjects')
  get '/subject/:id', to: 'public/base#subject_databases'

  # landing pages
  get '/about/:uuid', to: 'public/about#index'

  # url connection
  get '/connect/:uuid', to: 'public/connect#index'

  # CAS
  # ------------------------------------------------------------------
  get '/login',
      to: 'application#login',
      as: 'login'

  get '/signout',
      to: 'application#signout',
      as: 'signout'

  get '/logout',
      to: 'application#logout',
      as: 'logout'

  # ADMIN
  # ------------------------------------------------------------------
  get '/admin', to: 'admin#home', as: 'admin'

  namespace :admin do
    # databases
    get '/databases/list', to: 'databases#listall'
    get '/databases/list/:status', to: 'databases#list'
    get '/databases/tables', to: 'databases#tables'
    get '/databases/tables/:status', to: 'databases#tables'
    get '/databases/libguides', to: 'databases#lib_guides'
    resources :databases

    # import databases
    get '/import', to: 'databases#import'
    post '/import', to: 'databases#csv_import'

    # vendors
    resources :vendors

    # resources
    resources :resources

    # subjects
    resources :subjects
    get '/curated', to: 'subjects#curated', as: 'curated'
    get '/curated/:subject/sort', to: 'subjects#sort', as: 'sort_curated'
    post '/curated', to: 'subjects#update_curated', as: 'update_curated'

    # landing pages
    resources :landing_pages

    # users
    resources :users

    # link tracking
    resources :link_tracking

    # statistics
    get '/stats', to: 'statistics#show_all', as: 'csv_stats_all'
    get '/stats/:start_date/:end_date', to: 'statistics#show', as: 'csv_stats_filtered'
    #resources :statistics

    # get '/stats' to: 'statistics#show_all', as: 'stats'

    # admin/stats/10-22-2018/10-22-2021
    # get '/stats/:start_date/:end_date', to: 'statistics#show'
    # get 'stats' to: 'statistics#show_all'
  end
end

databases/app/views/admin/resources/_form.html.erb
<%= form_for [:admin, resource], html: { multipart: true } do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset> 
    <legend> Resource Information </legend>

    <div class="field">
      <%= form.label :name, class: 'required' %>
      <%= form.text_field :name %>
    </div>
  </fieldset>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

databases/app/views/admin/resources/edit.html.erb
<h1>Editing Admin Resource</h1>

<%= render 'form', resource: @resource %>

databases/app/views/admin/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Resources</h2>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th colspan="2"> Actions </th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td data-label="Name"> <%= resource.name %> </td>
        <td data-label="Edit"> <%= link_to raw('<span class="fas fa-edit"></span>'), edit_admin_resource_path(resource), { class: 'edit-button', title: 'Edit' } %> </td>
        <td data-label="Delete"> <%= link_to raw('<span class="fas fa-trash"></span>'), admin_resource_path(resource), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'Delete' %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Resource', new_admin_resource_path %>

databases/app/views/admin/resources/new.html.erb
<h2>New Resource</h2>

<%= render 'form', resource: @resource %>

databases/app/views/admin/resources/show.html.erb
<h2> <%= @resource.name %> </h2>

<%= link_to 'Edit', edit_admin_resource_path(@resource) %> |
<%= link_to 'Back', admin_resources_path %>