databases/config/routes.rb
Rails.application.routes.draw do
  # FRONTEND
  # ------------------------------------------------------------------
  root to: 'public/base#index'
  get '/', to: 'public/base#index'

  # Search
  get '/search(/:page)', to: 'public/search#index'

  # Feedback
  get '/feedback(/:db_id)', to: 'public/feedback#index'
  post '/feedback', to: 'public/feedback#email_submission'

  # Reporting
  get '/report(/:db_id)', to: 'public/report#index'
  post '/report', to: 'public/report#error_report'

  # A to Z Listings
  get '/AtoZ', to: 'public/base#all'
  get '/AtoZ/:character', to: 'public/base#a_to_z'

  # Subject Listings
  get '/subject', to: 'public/base#subject'
  get '/subjects', to: 'public/base#subject'
  get '/databases/subjects', to: redirect('/subjects')
  get '/subject/:id', to: 'public/base#subject_databases'

  # landing pages
  get '/about/:uuid', to: 'public/about#index'

  # url connection
  get '/connect/:uuid', to: 'public/connect#index'

  # CAS
  # ------------------------------------------------------------------
  get '/login',
      to: 'application#login',
      as: 'login'

  get '/signout',
      to: 'application#signout',
      as: 'signout'

  get '/logout',
      to: 'application#logout',
      as: 'logout'

  # ADMIN
  # ------------------------------------------------------------------
  get '/admin', to: 'admin#home', as: 'admin'

  namespace :admin do
    # databases
    get '/databases/list', to: 'databases#listall'
    get '/databases/list/:status', to: 'databases#list'
    get '/databases/tables', to: 'databases#tables'
    get '/databases/tables/:status', to: 'databases#tables'
    get '/databases/libguides', to: 'databases#lib_guides'
    resources :databases

    # import databases
    get '/import', to: 'databases#import'
    post '/import', to: 'databases#csv_import'

    # vendors
    resources :vendors

    # resources
    resources :resources

    # subjects
    resources :subjects
    get '/curated', to: 'subjects#curated', as: 'curated'
    get '/curated/:subject/sort', to: 'subjects#sort', as: 'sort_curated'
    post '/curated', to: 'subjects#update_curated', as: 'update_curated'

    # landing pages
    resources :landing_pages

    # users
    resources :users

    # link tracking
    resources :link_tracking

    # statistics
    get '/stats', to: 'statistics#show_all', as: 'csv_stats_all'
    get '/stats/:start_date/:end_date', to: 'statistics#show', as: 'csv_stats_filtered'
    #resources :statistics

    # get '/stats' to: 'statistics#show_all', as: 'stats'

    # admin/stats/10-22-2018/10-22-2021
    # get '/stats/:start_date/:end_date', to: 'statistics#show'
    # get 'stats' to: 'statistics#show_all'
  end
end

databases/app/models/database.rb
# The main model for storing academic databases. 
# NOT DATABASE CONNECTIONS!
# @author David J. Davis
# @modified_by Tracy A. McCormick
# @modified_on 2024-07-25

require 'csv'
class Database < ApplicationRecord
  # TABLE NAME
  # -----------------------------------------------------
  self.table_name = :database_list

  # VALIDATIONS
  # -----------------------------------------------------
  validates :name,
            presence: true,
            length: { within: 2..190 }

  validates :url_uuid,
            uniqueness: { case_sensitive: true },
            length: { within: 2..50 }

  validates :libguides_id, 
            numericality: { :only_integer => true, :allow_nil => true }
  validates_uniqueness_of :libguides_id, :allow_blank => true, :allow_nil => true


  validates :years_of_coverage,
            length: { maximum: 50 }

  validates :url,
            presence: true,
            url: true

  validates :description,
            presence: true

  # Validate URL's *optional presence
  validates :help_url, url: { allow_nil: true }
  # validates :off_campus_url, url: { allow_nil: true }

  # Boolean Validations
  # https://github.com/thoughtbot/shoulda-matchers/issues/512#issuecomment-50213690
  validates :popular, inclusion: { in: [true, false] }
  validates :new_database, inclusion: { in: [true, false] }
  validates :disable_proxy, inclusion: { in: [true, false] } 
  validates :trial_database, inclusion: { in: [true, false] }
  validates :open_access, inclusion: { in: [true, false] }
  validates :alumni, inclusion: { in: [true, false] }

  # ENUMS
  # -----------------------------------------------------
  enum status: { undefined: 0, production: 1, development: 2, hidden: 3 }
  validates :status, presence: true

  enum access: { 'Campus Only Access (No Proxy)' => 1, 
                 'Campus and Off Campus (Proxy)' => 2  }

  # ASSOCIATIONS
  # -----------------------------------------------------
  belongs_to :vendor, optional: true, required: false
  belongs_to :access_type, optional: true, required: false
  belongs_to :access_plain_text, optional: true, required: false

  # resources 
  has_many :database_resources, dependent: :destroy
  has_many :resources, through: :database_resources

  # subjects
  has_many :database_subjects, dependent: :destroy
  has_many :subjects, through: :database_subjects

  # curated subjects
  has_many :database_curated, dependent: :destroy
  has_many :curated, through: :database_curated, source: :subject

  # landing page
  has_one :landing_page, required: false, dependent: :destroy

  # link tracking
  has_many :link_tracking, dependent: :destroy

  # CONCERNS
  # -----------------------------------------------------
  include Searchable

  # RAILS CALLBACKS
  # -----------------------------------------------------
  # default values
  before_validation :mint_uuid, on: [:create]
  after_initialize :set_defaults
  # sanitize description only basic html tags allowed
  before_save :sanitize_description

  # SCOPES
  # -----------------------------------------------------
  scope :prod, -> { where(status: 'production') }
  scope :dev, -> { where(status: 'development') }
  scope :hide, -> { where(status: 'hidden') }
  scope :with_status, ->(status) { where(status: status) }
  scope :trials, -> { where(trial_database: true).where('trial_expiration_date > ?', DateTime.now) }
  scope :no_vendor, -> { where(vendor: nil) }
  scope :pop_list, -> { where(popular: true) }
  scope :new_list, -> { where(new_database: true) }
  scope :open_access_list, -> { where(open_access: true) }

  # scoping for alphabetical listing by titles
  scope :alpha_list, ->(letter) { where("name LIKE ?", "#{letter}%") }
  scope :number_list, -> { where("name REGEXP '^[0-9]'")}

  # scoping for subject listing 
  scope :list_subjects, -> (id) { includes(:subjects, :curated).order(:name).where(subjects: {id: id }) }
  scope :letters, -> { all.prod.order('name ASC').group_by{ |db| db.name[0].upcase }.keys.reject { |i| i =~ /\A\d+\z/ }.uniq } 
  scope :grouped_alpha, -> { all.prod.order('name ASC').group_by{ |db| db.name[0].upcase } } 
  scope :total_count, -> { all.prod.count }

  # PUBLIC METHODS
  # -----------------------------------------------------

  # Returns number of link_tracking assocations
  # Only used for reporting purposes
  # @author Tracy A. McCormick
  # @return integer
  def tracking_total_count
    link_tracking.count
  end

  # Uses Enum method to determine if something is published.
  # Only used in the search params for elasticsearch
  # @author David J. Davis
  # @return Boolean
  def published
    self.production?
  end

  # Creates keywords for indexing, filtering, search etc.
  # @author David J. Davis
  # @return string
  def keywords
    attr = [status, name, title_search, subject_list]
    attr.join(' ')
  end

  # Creates comma seperated list of subjects.
  # @author David J. Davis
  # @return string
  def subject_list
    list = []
    subjects.each { |subject| list << subject.name }
    list.to_sentence
  end

  # Creates groupings of subjects seprated by semi-colons. 
  # @author David J. Davis
  # @return string
  def subjects_column
    list = []
    subjects.each { |subject| list << subject.name }
    list.join(';')
  end

  # Creates groupings of resources seprated by semi-colons.
  # @author David J. Davis
  # @return string
  def resources_column
    list = []
    resources.each { |rss| list << rss.name }
    list.join(';')
  end

  # Creates comma seperated list of resources.
  # @author David J. Davis
  # @return string
  def resource_list
    list = []
    resources.each { |rss| list << rss.name }
    list.to_sentence
  end

  # Returns an array of names for search index.
  # @author David J. Davis
  # @return [Array]
  def subject_search_index
    subjects.pluck(:name)
  end

  # Returns an array of names for search index.
  # @author David J. Davis
  # @return [Array]
  def rss_search_index
    resources.pluck(:name)
  end

  # Returns an array of names for search index.
  # @author David J. Davis
  # @return [Array]
  def curated_search_index
    curated.pluck(:name)
  end

  # Calls the association for vendor unless nil, and returns the vendors name. 
  # @author David J. Davis
  # @return string or nil
  def vendor_name
    vendor&.name
  end

  # Checks to see if the campus only designation is set 
  # @author David J. Davis
  # @return boolean
  def campus_only?
    access == 'Campus Only Access (No Proxy)'
  end

  def connect_url
     'https://databases.lib.wvu.edu/connect/' + url_uuid
  end

  # Creates a csv object of all database records.
  # @author David J. Davis
  # @return csv object
  def self.to_csv
    CSV.generate(headers: true) do |csv|
      attributes = %w[
        id libguides_id name status years_of_coverage vendor_name url access 
        full_text_db help help_url description url_uuid new_database popular
        trial_database trial_expiration_date title_search subjects_column
        resources_column created_at updated_at
      ]

      csv << attributes.map(&:better_titleize)
      all.find_each do |database|
        csv << attributes.map { |attr| database.send(attr) }
      end
    end
  end 

  # Generates a CSV to populate libguides a-to-z listing.
  # @author David J. Davis
  # @return csv object
  def self.libguides_export
    headers = %w[
      vendor name url enable_proxy description more_info enable_new
      enable_trial types keywords target slug best_bets subjects
      desc_pos lib_note enable_popular enable_hidden internal_note
      owner resource_icons thumbnail content_id
    ]
    CSV.generate(headers: true) do |csv|
      csv << headers
      # get everything else
      all.find_each do |database|
        database.url = database.connect_url
        csv << database.csv_hash.values
      end
    end
  end


  # New version of libguides_export that includes new field-mappings in export.   
  # Generates a CSV to populate libguides a-to-z listing.
  # @author Praneeth Byna
  # @return csv object
  def self.libguides_export_v2
    headers = [
    "DATABASE NAME",
    "PUBLIC DATABASE DISPLAY",
    "DATABASE LANDING PAGE",
    "DATABASE URL",
    "USE PROXY?",
    "FRIENDLY URL",
    "DATABASE LANDING PAGE FRIENDLY URL",
    "ALTERNATE NAMES",
    "KEYWORDS & MISSPELLINGS",
    "DATABASE DESCRIPTION",
    "VENDOR",
    "TYPES",
    "ASSOCIATED SUBJECTS",
    "BEST BETS",
    "ATTRIBUTES",
    "FLAGS",
    "THUMBNAIL URL",
    "THUMBNAIL ALT TEXT",
    "MORE INFO",
    "LIBRARIAN REVIEW",
    "INTERNAL NOTE",
    "ACCESS MODES",
    "OWNER",
    "RESOURCE ICONS",
    "PERMITTED USES"
    ]
    CSV.generate(headers: true) do |csv|
      csv << headers
      # get everything else
      all.find_each do |database|
        database.url = database.connect_url
        csv << database.csv_hash_v2.values
      end
    end
  end





  # Generates a CSV to export link tracking data.
  # @author Tracy A. McCormick
  # @return csv object
  def self.linktracking_export
    headers = %w[
      name count
    ]
    CSV.generate(headers: true) do |csv|
      csv << headers
      # get everything else
      all.find_each do |database|
        csv << database.link_tracking_all_csv_hash.values
      end
    end
  end  

  # Creates a hash to use in the lib_guides CSV.
  # LibGuides requries the use of these fields
  # vendor name url enable_proxy description more_info enable_new enable_trial
  # types keywords target slug best_bets subjects desc_pos lib_note
  # enable_popular enable_hidden internal_note owner resource_icons
  # thumbnail content_id
  # @author David J. Davis
  # @return [Hash] Custom for LibGuides.
  def csv_hash
    {
      vendor: self.vendor_name,
      name: self.name,
      url: self.url,
      enable_proxy: self.access == 2 ? 1 : 0,
      description: self.description,
      more_info: '',
      enable_new: self.new_database.to_i,
      enable_trial: self.trial_database.to_i,

databases/app/views/admin/databases/_form.html.erb
<%= form_for [:admin, database], html: { multipart: true } do |form| %>
  <% if database.errors.any? %>
    <div id="error_explanation" role="alert" aria-atomic="true">  
      <h2>
        <%= pluralize(database.errors.count, "error") %> 
        <%= I18n.t("admin.basic.error_prompt") %>
      </h2>

      <ul>
      <% database.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset> 
    <legend> <%= I18n.t("admin.databases.forms.basic_title") %> </legend>
    
    <div class="row"> 
      <div class="field three-fourth">
        <%= form.label :name, 'Title', class: 'required' %>
        <%= form.text_field :name %>
      </div>

      <div class="field one-fourth">
        <%= form.label :status, class: 'required' %>
        <div class="select-style">
          <%= form.select :status, options_for_select(Database.statuses.keys.to_a, selected: form.object.status), include_blank: I18n.t("admin.basic.forms.select_status") %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="field full">
        <%= form.label :url, class: 'required' %>
        <%= form.text_field :url %>
      </div>
    </div>

    <div class="row">
      <div class="field full">
        <%= form.label :description, class: 'required' %>
        <%= form.text_area :description %>
      </div>
    </div>

    <div class="row">
      <div class="field half"> 
        <%= form.label :vendor_id, "Vendor" %>
        <div class="select-style">
          <% vendor_id = form.object.vendor.id unless form.object.vendor.blank? %>
          <%= form.collection_select :vendor_id, Vendor.all.order(:name), :id, :name, selected: vendor_id, :prompt => true, :prompt => 'Select a Vendor ...' %>
          <%# form.select :vendor, Vendor.all.order(:name).collect {|v| [v.name, v.id]}, selected: vendor_id, :prompt => 'Select a Vendor ...' %>
        </div>
      </div>
      <div class="field half">
        <%= form.label :years_of_coverage %>
        <%= form.text_field :years_of_coverage %>
      </div>
    </div>

    <div class="row">
      <div class="field full">
        <%= form.label :title_search,  "Keywords" %>
        <div class="micro-text text-left"> 
          <%= I18n.t("admin.databases.forms.keyword_description") %>  
          <strong> 
            <%= I18n.t("admin.databases.forms.keyword_description_example") %>
          </strong> 
        </div>
        <%= form.text_field :title_search %>
      </div>
    </div>

  </fieldset>

  <fieldset>
    <legend> <%= I18n.t("admin.databases.forms.access_title") %> </legend>
    
    <div class="micro-text">
      <%= I18n.t("admin.databases.forms.access_description") %> 
    </div>

    <div class="row">
      <div class="field one-fourth">
        <%= form.label :alumni, 'Alumni Database' %>
        <div class="select-style">
          <%= form.select :alumni, options_for_select([['Yes', true], ['No', false]], selected: form.object.alumni) %>
        </div>
      </div>

      <div class="field one-fourth">
        <%= form.label :popular, 'Popular Database' %>
        <div class="select-style">
          <%= form.select :popular, options_for_select([['Yes', true], ['No', false]], selected: form.object.popular) %>
        </div>
      </div>

      <div class="field one-fourth">
        <%= form.label :full_text_db, 'Full Text Database' %>
        <div class="select-style">
          <%= form.select :full_text_db, options_for_select([['Yes', true], ['No', false]], selected: form.object.full_text_db) %>
        </div>
      </div>
      
      <div class="field one-fourth">
        <%= form.label :new_database %>
        <div class="select-style">
          <%= form.select :new_database, options_for_select([['Yes', true], ['No', false]], selected: form.object.new_database) %>
        </div>
      </div>

      <div class="field one-fourth">
        <%= form.label :open_access %>
        <div class="select-style">
          <%= form.select :open_access, options_for_select([['Yes', true], ['No', false]], selected: form.object.open_access) %>
        </div>
      </div>

      <div class="field one-fourth">
        <%= form.label :disable_proxy %>
        <div class="select-style">
          <%= form.select :disable_proxy, options_for_select([['Yes', true], ['No', false]], selected: form.object.disable_proxy) %>
        </div>
      </div>      
    </div>
  </fieldset>

  <fieldset>
    <legend> <%= I18n.t("admin.databases.forms.trial_title") %> </legend>
    <div class="micro-text">
       <%= I18n.t("admin.databases.forms.trial_description") %>
    </div>
    <div class="row">
      <div class="field one-fourth">
        <%= form.label :trial_database %>
        <div class="select-style">
          <%= form.select :trial_database, options_for_select([['Yes', true], ['No', false]], selected: form.object.trial_database) %>
        </div>
      </div>

      <div class="field three-fourth"> 
        <%= form.label :trial_expiration_date %>
        <%= form.date_field :trial_expiration_date %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend> <%= I18n.t("admin.databases.forms.help_title") %> </legend>
    <div class="micro-text">
      <%= I18n.t("admin.databases.forms.help_description") %>
    </div>
    
    <div class="field full">
      <%= form.label :help_url, "Help Link", class:"required" %>
      <%= form.text_field :help_url %>
    </div>

     <div class="field full">
      <%= form.label :help, "Help Description" %>
      <%= form.text_area :help %>
    </div>
  </fieldset>

  <fieldset>
    <legend> Informative Tags </legend>

    <div class="micro"> 
      <p> <%= raw I18n.t('admin.databases.forms.informative_tags_description.html') %> </p>
    </div><br/>

    <!-- Subject Field -->
    <div class="field">
      <%= form.label :subject_ids, 'Subjects' %>
      <input type="hidden" name="database[subject_ids][]" value=""/>
      <%= form.collection_select :subject_ids, 
                                 Subject.all.order(:name), 
                                 :id, 
                                 :name, 
                                 { include_hidden: false }, 
                                 { multiple: true } 
      %>
      
      <div class="half select">
        <a href='#' id='subject_select_all'> Select All </a>
      </div>
      
      <div class="half deselect">
        <a href='#' id='subject_deselect_all'> Deselect All </a>
      </div>
    </div>

    <!-- Curated Fields -->
    <div class="field">
      <%= form.label :curated_ids, 'Curated Subjects' %>
      <input type="hidden" name="database[curated_ids][]" value=""/>
      <%= form.collection_select :curated_ids, 
                                 Subject.all.order(:name), 
                                 :id, 
                                 :name, 
                                 { include_hidden: false }, 
                                 { multiple: true } 
      %>
      
      <div class="half select">
        <a href='#' id='curated_select_all'> Select All </a>
      </div>
      
      <div class="half deselect">
        <a href='#' id='curated_deselect_all'> Deselect All </a>
      </div>
    </div>

     <!-- Resource Fields -->
    <div class="field">
      <%= form.label :resource_ids, 'Resource Types' %>
      <input type="hidden" name="database[resource_ids][]" value=""/>
      <%= form.collection_select :resource_ids, 
                                 Resource.all.order(:name), 
                                 :id, 
                                 :name, 
                                 { include_hidden: false }, 
                                 { multiple: true } 
      %>
      
      <div class="half select">
        <a href='#' id='resource_select_all'> Select All </a>
      </div>
      
      <div class="half deselect">
        <a href='#' id='resource_deselect_all'> Deselect All </a>
      </div>
    </div>

  </fieldset>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

databases/app/views/admin/databases/edit.html.erb
<h1>Editing Database</h1>

<%= render 'form', database: @database %>

<%= link_to 'Show', admin_database_path(@database) %> |
<%= link_to 'Back', admin_databases_path %>

databases/app/views/admin/databases/import.html.erb
<h2> Database Import </h2>

<p> There is a possibility that the full import does not happen or something errors during this process.  We may not be able to inform you fully of any errors that happen during the bulk database importing and updating please be sure to check all information after the import completes. </p>

<%= form_for @database_import, url: '/admin/import', html: {multipart: true, class: 'report-form', method: 'post'} do |f| %>

  <% if @database_import.errors.any? %>
    <div id="error_explanation" class="full" role="alert" aria-atomic="true">  
      <h2>
        <%= pluralize(@database_import.errors.count, "error") %> 
        Prevented this form from being submitted! 
      </h2>

      <ul>
      <% @database_import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset> 
    <legend> Database CSV</legend>

    <div class="field full">
      <%= f.label :csv %>
      <%= f.file_field :csv %>
      <%= f.hidden_field :csv_cache %>
    </div>
  </fieldset>
  
  <div class="actions">
    <%= f.submit "Import Now", class: 'button' %>
  </div>

<% end %>

databases/app/views/admin/databases/index.html.erb
<!-- Should render tables instead -->

databases/app/views/admin/databases/list.html.erb
<h1><%= I18n.t('admin.databases.index.heading') %></h1>

<div class="container">
  <div class="search-filter">
    <label for="search_filter"> 
      <%= I18n.t('admin.databases.filter_label') %>
    </label>
    <input id="search_filter" type="text" class="reset search-dom" placeholder="Search Databases..."/>

    <div class="micro-text"> 
      <%= I18n.t('admin.databases.filter_warning') %>
    </div>
  </div>
</div>

<section class="database-cards">
  <% @databases.each do |database| %>
    <div class="database filter-list">
        <div class="hidden keywords"> 
          <%= database.keywords.strip %>
        </div>

        <h2 id="<%= database.id %>"> <%= database.name %> </h2>
        <dl>
          <dt> Status </dt> 
          <dd> <%= database.status %> </dd>

          <dt> Campus Url </dt>
          <dd> <%= database.url %> </dd>

          <dt> Vendor </dt>
          <dd> <%= database.vendor.name unless database.vendor.nil? %> </dd>

          <dt> Access </dt>
          <dd> <%= database.access_plain_text.name  unless database.access_plain_text.nil? %> </dd>
          <dd> <%= database.access_type.name unless database.access_type.nil? %> </dd>

          <dt> Trial </dt>
          <dd> <%= database.trial_database ? "Yes" : "No" %> </dd>
          <% if database.trial_database %>  
            <dd> <%= database.trial_expiration_date %> </dd>
          <% end %>

          <dt> Subjects </dt>
          <dd> <%= database.subject_list %> </dd>
        </dl> 

      <div class="actions"> 
        <%= link_to raw('<span class="fas fa-eye"></span>'), admin_database_path(database), { class: 'show-button', title: 'Show', 'aria-label':"Show #{database.name}" } %>
        <%= link_to raw('<span class="fas fa-edit"></span>'), edit_admin_database_path(database), { class: 'edit-button', title:'Edit', 'aria-label':"Edit #{database.name} " } %>
        <%= link_to raw('<span class="fas fa-trash"></span>'), admin_database_path(database), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'Delete', 'aria-label':"Delete #{database.name}"  %>
      </div>
    </div>
  <% end %>
</section>

databases/app/views/admin/databases/new.html.erb
<h1>New Admin Database</h1>

<%= render 'form', database: @database %>

<%# link_to 'Back', admin_databases_path %>

databases/app/views/admin/databases/show.html.erb
<div class="database-show">
  <div class="container">
    <h2> <%= @database.name %> </h2>
    <p> 
      <%= raw @database.description %> 
    </p>
  </div>

  <div class="container"> 
    <h3> Database Information </h3>
    <p> <strong> UUID </strong> <%= @database.url_uuid %> </p>
    <p> <strong> ID </strong> <%= @database.id %> </p>
    <p> <strong> Landing Page </strong> <%= @database.landing_page ? "Yes" : "No" %> </p>
    <p> <strong> Status </strong> <%= @database.status %> </p> 
    <p> <strong> Years of Coverage </strong> <%= @database.years_of_coverage %> </p> 
  </div>

  <div class="container"> 
  <h3> Vendor Information </h3> 
    <p>
    <% if @database.vendor_name.nil? %>
      No Vendor Name Supplied
    <% else %>
    <strong> Vendor Name </strong> 
      <%= @database.vendor_name unless @database.vendor_name.nil? %> 
    <% end %>
    </p>

    <p> 
      <strong> URL </strong> 
      <%= @database.url %>
    </p>

    <% unless @database.off_campus_url %>
      <strong> Off Campus URL </strong>
      <%= @database.off_campus_url %>
    <% end %>
  </div>

  <div class="container"> 
    <h3> Database Subjects </h3>
    <%= @database.subject_list %>
  </div>

  <div class="container"> 
    <h3> Curated Subjects </h3>
    <%= @database.curated_search_index.to_sentence %>
  </div>

  <div class="container"> 
    <h3> Database Resources </h3>
    <%= @database.resource_list %>
  </div>

  <div class="container">
    <h3> Database Types / Access Types </h3> 

    <div class="four-col">
      <strong> Alumni Database </strong> 
      <%= @database.alumni ? "Yes" : "No" %>
    </div> 
    <div class="four-col">
      <strong> Popular Database </strong> 
      <%= @database.popular ? "Yes" : "No" %>
    </div>
    <div class="four-col">
      <strong> Full Text Database </strong> 
      <%= @database.full_text_db ? "Yes" : "No" %>
    </div>
    <div class="four-col">
      <strong> New Database </strong> 
      <%= @database.new_database ? "Yes" : "No" %>
    </div>
    <div class="four-col">
      <strong> Open Access </strong> 
      <%= @database.open_access ? "Yes" : "No" %>
    </div>
    <div class="four-col">
      <strong> Disable Proxy </strong> 
      <%= @database.disable_proxy ? "Yes" : "No" %>
    </div>
  </div>

  <div class="container">
    <h3> Trial Information </h3> 
    <p>
      <strong> Trial Database </strong> 
      <%= @database.trial_database ? "Yes" : "No" %>
    </p>
    <p> 
      <strong> Trial Expiration </strong>
      <% unless @database.trial_expiration_date.nil? %>
        <%= @database.trial_expiration_date.strftime("%B %d, %Y at %I:%M%p") %>
      <% else %>
        N/A
      <% end %>
    </p>
  </div>

  <div class="container"> 
    <h3> Search Keywords </h3>
    <p>
      <strong> Basic Keywords </strong>
      <%= @database.title_search %>
    </p>
    
    <p> 
      <strong> Full Index </strong> <br/> 
      <%= @database.keywords %>
    </p>
  </div>


  <div class="container"> 
    <h3> Created / Updated </h3> 
    <p class="datestamp">
      Created at <%= @database.created_at.strftime("%B %d, %Y at %I:%M%p") %> 
    </p>
    <p class="datestamp">
      Updated at <%= @database.updated_at.strftime("%B %d, %Y at %I:%M%p")%>
    </p>
  </div>
  
  <%= link_to 'Edit', edit_admin_database_path(@database) %> |
  <%= link_to 'Back', admin_databases_path %>

</div>

databases/app/views/admin/databases/table.html.erb
<h1><%= I18n.t('admin.databases.index.heading') %></h1>

<table class="table">
  <thead>
    <tr> 
      <th> Title </th>
      <th> Status </th>
      <th> Vendor </th>
      <th> Trial </th>
      <th> Trail Expiration </th>
      <th colspan="3"> Actions </th>
    </tr>
  </thead>
  
  <% @databases.each do |database| %>
    <tr> 
      <td data-label="Title"> <%= database.name %> </td>
      <td data-label="Status"> <%= database.status %> </td>
      <td data-label="Vendor"> <%= database.vendor_name %> </td>
      <td data-label="Trial"> <%= database.trial_database ? "Yes" : "No" %> </td>
      <td data-label="Trial Date"> <%= l(database.trial_expiration_date, format: :human_readable) unless database.trial_expiration_date.nil? %> </td>
      <td data-label="Show"> <%= link_to raw('<span class="fas fa-eye" title="Show"></span>'), admin_database_path(database), { class: 'show-button', title:'show', 'aria-label':"Show #{database.name}" } %> </td>
      <td data-label="Edit"> <%= link_to raw('<span class="fas fa-edit" title="Edit"></span>'), edit_admin_database_path(database), { class: 'edit-button', title:'edit', 'aria-label':"Edit #{database.name}" } %> </td>
      <td data-label="Destroy"> <%= link_to raw('<span class="fas fa-trash" title="Delete"></span>'), admin_database_path(database), method: :delete, class: 'delete-button', data: { confirm: 'Are you sure?' }, title:'delete', 'aria-label':"Delete #{database.name}" %> </td>
    </tr>
  <% end %>
</table>